# Generated by Django 5.2.4 on 2026-05-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_invoice_billing_address_invoice_billing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_sections/'),
        ),
    ]
