# Generated by Django 5.2.4 on 2026-05-25 11:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_menusection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(help_text='Banner image', upload_to='ad_banners/')),
                ('link_url', models.URLField(blank=True, help_text='Where the banner should link to', max_length=500, null=True)),
                ('cta_text', models.CharField(default='Learn More', help_text='Call to Action button text', max_length=50)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for never expire', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Number of clicks')),
                ('impressions', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(blank=True, help_text='Specific restaurant for this ad (leave blank for global ads)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_banners', to='dashboard.restaurant')),
            ],
            options={
                'verbose_name': 'Ad Banner',
                'verbose_name_plural': 'Ad Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
