# Generated by Django 5.2.4 on 2026-05-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_adbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark as favorite for special promotion'),
        ),
    ]
