# Generated by Django 5.2.4 on 2026-05-31 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_cart_options_alter_order_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_guest_cart_item',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='dashboard_c_user_id_26d5a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='dashboard_c_session_895dfb_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='dashboard_o_session_dc028e_idx',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='order',
            name='session_key',
        ),
        migrations.AddField(
            model_name='cart',
            name='guest_id',
            field=models.CharField(blank=True, db_index=True, help_text='UUID generated by mobile app for guest users', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Calculated delivery distance in kilometers', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Delivery location latitude (e.g., 27.7172453)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Delivery location longitude (e.g., 85.3239605)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_id',
            field=models.CharField(blank=True, db_index=True, help_text='UUID from Flutter for guest users', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate (e.g., 27.717245)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate (e.g., 85.323960)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='e.g. No onions, Extra cheese'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Free for ≤5km, NPR 100 for >5km', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Order Received'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('picked_up', 'Picked Up'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Will be calculated dynamically based on tax percentage', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=13.0, help_text='Nepal VAT 13%', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='dashboard_c_user_id_56545f_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['guest_id'], name='dashboard_c_guest_i_76692d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['guest_id'], name='dashboard_o_guest_i_9832b5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_latitude', 'delivery_longitude'], name='dashboard_o_deliver_dcc82d_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_id__isnull', False), ('user__isnull', True)), fields=('guest_id', 'menu_item'), name='unique_guest_cart_item'),
        ),
    ]
