# Generated by Django 5.2.4 on 2026-06-02 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_order_landmark_alter_order_order_number_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'address_type')},
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('user', 'address_type'), name='unique_address_per_type'),
        ),
    ]
