# Generated by Django 5.2.4 on 2026-06-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_address_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_address_per_type',
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
    ]
