# Generated by Django 5.2.4 on 2026-06-02 11:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_address_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_address_per_type',
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'is_default')},
        ),
    ]
