# Generated by Django 5.2.4 on 2026-06-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_address_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='location',
            field=models.CharField(blank=True, help_text="Location string like 'M88R+HPR, Imadol, Bagmati Province'", max_length=500, null=True),
        ),
    ]
